[package]
name = "magiebleue"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
gl = "0.14.0"
glfw = "0.61.0"
imagine = "0.5.3"
noise = "0.9.0"
ultraviolet = { version = "0.10.0", features = [ "int" ] }
